---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-nmstate

resources:
  - nmstate.yaml
  - role.yaml
  - clusterrole.yaml
  - rolebinding.yaml
  - clusterrolebinding.yaml
