---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-gitops-argocd-server-nmstate
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nmstate-mgr
subjects:
  #- kind: ServiceAccount
  #name: openshift-gitops-argocd-server
  #namespace: openshift-gitops
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops


#  Partial sync operation to failed: one or more objects failed to apply, reason: nmstates.nmstate.io is forbidden: User "system:serviceaccount:openshift-gitops:openshift-gitops-argocd-application-controller" cannot create resource "nmstates" in API group "nmstate.io" at the cluster scope
