# oc create role metallb-mgr --verb='*' --resource=MetalLB -n metallb-system --dry-run=client -o yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: nmstate-mgr
  namespace: openshift-nmstate
rules:
- apiGroups:
  - nmstate.io
  resources:
  - nmstates
  - nmstateconfigs
  - nodenetworkconfigurationpolicies
  verbs:
  - '*'
